version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6.16
        ports:
           - 5441:5432
        environment:
           - POSTGRES_PASSWORD=secret
           - POSTGRES_USER=pguser
           - POSTGRES_DB=myfinances 
        expose:
           - 5441  
        networks: 
            - production-network
    myfinances-api:
        container_name: myfinances-api
        build:
            dockerfile: ./Dockerfile
            context: ./myfinances
        image: myfinances-api
        ports:
            - "9090:8080"
        expose:
            - 9090  
        networks: 
            - production-network
        depends_on:
            - postgres
            - myfinances-api-monitor
    myfinances-api-monitor:
        container_name: myfinances-api-monitor
        build:
            dockerfile: ./Dockerfile
            context: ./myfinances.monitor
        image: myfinances-api-monitor
        ports:
            - "9091:8081"
        expose:
            - 9091  
        networks: 
            - production-network
        depends_on:
            - postgres
            
networks: 
    production-network:
        driver: bridge