version: '3'
services:
  postgres-myfinances:
    container_name: postgres-myfinances
    image: postgres:9.6.16
    restart: always
    command: -p 5441
    ports:
      - 5441:5441
    environment:
      - POSTGRES_PASSWORD=4b28121d3c291f5c2b561ddc3e999cf589ddbe6472e202edf058106d069fc74e
      - POSTGRES_USER=myfinances87%w2
      - POSTGRES_DB=myfinancesdb
    expose:
      - 5441
    networks:
      - production-network
  myfinances-api:
    container_name: myfinances-api
    build:
      args:
        - PORT=8080
        - SPRING_PROFILES_ACTIVE=prod
        - MEMORY_USE=
      dockerfile: ./Dockerfile
      context: ./myfinances
    image: myfinances-api
    restart: always
    environment:
      - POSTGRESQL_HOST=postgres-riskcontrol
      - SPRING_DATASOURCE_USERNAME=riskcontroluser87%w2
      - SPRING_DATASOURCE_PASSWORD=4b28121d3c291f5c2b561ddc3e999cf589ddbe6472e202edf058106d069fc74e
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-riskcontrol:5441/riskcontroldb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - WAIT_HOSTS=postgres-riskcontrol:5441
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=7070
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - production-network
    depends_on:
      - postgres-myfinances

  myfinances-api-monitor:
    container_name: myfinances-api-monitor
    build:
      args:
        - PORT=8081
        - SPRING_PROFILES_ACTIVE=default
        - MEMORY_USE=-Xmx512m
      dockerfile: ./Dockerfile
      context: ./myfinances.monitor
    image: myfinances-api-monitor
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - production-network
    depends_on:
      - postgres

  myfinances-ui:
    container_name: myfinances-ui
    build:
      dockerfile: ./Dockerfile
      context: ./myfinances-ui
    image: myfinances-ui
    restart: always
    ports:
      - "80:80"
    expose:
      - 80
    environment:
      - PORT=80
      - NGINX_HOST=http://myfinances-api:7070
    networks:
      - production-network
    depends_on:
      - myfinances-api

networks:
  production-network:
    driver: bridge
